services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: races
      POSTGRES_USER: mpu
      POSTGRES_PASSWORD: mpu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - horse-races-network

  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend/horse-races
    ports:
      - "9000:80"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/races
      SPRING_DATASOURCE_USERNAME: mpu
      SPRING_DATASOURCE_PASSWORD: mpu
    depends_on:
      - postgres
    entrypoint: ["./wait-for-it.sh", "postgres:5432", "--"]
    command: ["java", "-jar", "your-backend-application.jar"]
    networks:
      - horse-races-network


  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend/horse-races
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - horse-races-network


volumes:
  postgres_data:
    driver: local

networks:
  horse-races-network:
    driver: bridge