services:
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend/horse-races
    ports:
      - "8080:80"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/races
      SPRING_DATASOURCE_USERNAME: mpu
      SPRING_DATASOURCE_PASSWORD: mpu
    depends_on:
      - postgres
    networks:
      horse-races-network:
        ipv4_address: 172.20.0.2

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend/horse-races
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      horse-races-network:
        ipv4_address: 172.20.0.3

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: races
      POSTGRES_USER: mpu
      POSTGRES_PASSWORD: mpu
    ports:
      - "8284:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      horse-races-network:
        ipv4_address: 172.20.0.4

volumes:
  postgres_data:
    driver: local

networks:
  horse-races-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
